### ISSUE TITLE
haveSameAspectRatio 

### ISSUE THREAD

**Issue by alaeri** [flavioarfaria/KenBurnsView#17]
I had a weird crash when I rotated my tablet several times with the view enabled. I have pinpointed it to the MathUtils.haveSameAspectRatio() function, and the truncation...

If my previous destRect had a ratio of 0.637 and my new viewPort has a rect ratio of 0.625
The function will say that the viewPortRatio has not changed. (even if we can tell right now that the difference between the two is more than 0.01)

If the random rect generator, provided with a viewport with a 0.625 ratio then returns a rect with a ratio of 0.624999, this will raise the IncompatibleRatioException in the Transition constructor.

I believe the truncating is not that good of an idea when you are comparing the aspect ratios. Imho, it should at least be one decimal further than the comparison itself.

**Comment by Vilgan** [comment]
I haven't been able to repro this, but another dev got a stack trace that also threw this exception. @flavioarfaria can you describe the downsides of adding another decimal point of precision? I'm tempted to do that, but don't understand the downsides of doing so.
