### ISSUE TITLE
choppy/glitchy on image load

### ISSUE THREAD

**Issue by schwiz** [flavioarfaria/KenBurnsView#20]
Great library thanks for sharing, I am having a slight issue though. When I load an image it seems to jump quickly between a few transitions before settling on one and going through it.  

Kind of hard to explain so I can upload a video if needed, but basically my image will jump around to different scale sizes before finally picking one and smoothly doing the Ken Burns effect.

**Comment by flavioarfaria** [comment]
Hi schwiz, thank you for your report. I'd be glad if you could provide some steps to reproduce it. Anything like a video and/or a simple project demonstrating the issue would help a lot.

**Comment by schwiz** [comment]
Turned out to be pilot error. I was setting the image more than one time which would generate a new transition even though the previous had only just started.
