### ISSUE TITLE
Pausing the KenBurnsView animaiton makes the image inside too small

### ISSUE THREAD

**Issue by aritraroy** [flavioarfaria/KenBurnsView#26]
When the animation plays, its perfectly fine. But when I use view.pause() then the animations stops but the image becomes very small in size. 

How can this problem be solved? I need to give the users a way to stop the animation of this View if they want to.

**Comment by flavioarfaria** [comment]
Did you try the sample app? That's not happening. Could you provide steps to reproduce it?

**Comment by aritraroy** [comment]
This is my XML

<com.flaviofaria.kenburnsview.KenBurnsView
                android:id="@+id/nav_header_cover"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:src="@drawable/cover_1" />

This is how I set the drawable programatically,

Drawable drawable = Drawable.createFromPath(fileName.getAbsolutePath());
navHeader.setImageDrawable(drawable);

This is how I am playing/pausing it,

if (isAnimOn)
            navHeader.resume();
        else 
            navHeader.pause();

Can you please point out what is the mistake here?

**Comment by aritraroy** [comment]
I have tried a lot, but still have the problem. Any help?

**Comment by Pkmmte** [comment]
I'm having this same issue...
