### ISSUE TITLE
Define zoom/pan start position

### ISSUE THREAD

**Issue by fakir22** [flavioarfaria/KenBurnsView#31]
Hi,
the overview or this nice library says the following:  "Highly extensible: you can define how the rectangles to be zoomed and panned will be generated"
and that's exactly what I want to do but I don't know exactly how. 

I would like to be able to tell the library to zoom or pan from a specified region (a RectF I presume) of my image.
I think I have to implements my own TransitionGenerator and write a custom generateNextTransition() mtehod but I don't know what to do inside.

Can you help me ?

Thanks.
Adrian

**Comment by LiuDeng** [comment]
solve this？

**Comment by i-com-dijon** [comment]
The author of the KenBurnsView plugin answered my question on stackoverflow. See his great response right here : http://stackoverflow.com/questions/31958739/define-zoom-pan-start-position-with-kenburnsview
;)
