### ISSUE TITLE
Slide Show

### ISSUE THREAD

**Issue by davidengler** [flavioarfaria/KenBurnsView#35]
Can we add option to give an assets folder and show a slide show of the images?

**Comment by flavioarfaria** [comment]
Hi David,

Thanks for your suggestion.

In order to keep KenBurnsView as minimal as possible, I think it'd be more suitable that your suggestion would be implemented as a new library on top of KenBurnsView. This way, people that doesn't need such feature would not need to ship it in their apps.

**Comment by davidengler** [comment]
Sure, Thank you :)
