### ISSUE TITLE
support for shared element transition?

### ISSUE THREAD

**Issue by suhaibroomy** [flavioarfaria/KenBurnsView#41]
I am using ken burns in a toolbar and i want shared element transition . so basically an imageview would be shared with the previous activity, in the current implementation you are restarting the animation in onsizechanged which doesnt give a nice effect.can you provide any support. my solution to restart the animation after the callback of shared element transition and then using the image view rect as src and then exapanding it to a rect required by kenbens to work and then start the animation

**Comment by flavioarfaria** [comment]
Hi suaibroomy,

Currently, KenBurnsView doesn't provide any support for shared element transitions. That would involve sharing drawables across activities and it's currently out of the scope of this library. You can, however, try to share the `TransitionGenerator` and the current `Transition` across activities. I haven't try this, but that could work.
